BOARD_TAG = uno
ARDUINO_PORT = /dev/ttyS5 	# n is COM port number
# USER_LIB_PATH = ~/Arduino/libraries
#USER_LIB_PATH = $(HOME)/sketchbook/libraries
USER_LIB_PATH = libraries
ARDUINO_LIBS = Wire LEVEL GFX IL19341 SPI
include /usr/share/arduino/Arduino.mk