BOARD_TAG = uno
DEVICE_PATH = /dev/ttyS5 	# n is COM port number
# USER_LIB_PATH = ~/Arduino/libraries
USER_LIB_PATH = $(HOME)/sketchbook/libraries
ARDUINO_LIBS = Wire LEVEL GFX IL19341
include /usr/share/arduino/Arduino.mk